# Generated by Django 6.0.3 on 2026-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfaq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='faq',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
