# Generated by Django 6.0.3 on 2026-04-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfaq', '0002_alter_faq_options_faq_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to='faq_midia/'),
        ),
    ]
