# Generated by Django 6.0.3 on 2026-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfaq', '0003_faq_midia'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='privado',
            field=models.BooleanField(default=False),
        ),
    ]
